
version: "3"
services:
  web:
    build: .
    container_name: RTM
    build: .
    ports:
      - "5004:80"
    depends_on:
      - db
    
  db:
    image: "mongo:latest"
    container_name: mongodbnew
    ports:
      - "27017:27017"

